run:
	@gcc day2part2.c -o day2part2
	@./day2part2 input

test:
	@gcc day_2.c -o day_2
	@./day_2 12 13 14 test

test2:
	@gcc day2part2.c -o day2part2
	@./day2part2 test

day_2:
	@gcc day_2.c -o day_2
	@./day_2 input

clean:
	@rm day_2

